plugins {
    id 'groovy-gradle-plugin'
}

repositories {
    gradlePluginPortal()
    mavenCentral()
}

apply from: './properties.gradle'

// https://stackoverflow.com/a/66897652
dependencies {
    // https://mvnrepository.com/artifact/org.graalvm.buildtools.native/org.graalvm.buildtools.native.gradle.plugin
    // https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html#_adding_the_plugin
    implementation 'org.graalvm.buildtools.native:org.graalvm.buildtools.native.gradle.plugin:1.1.4'
    // implementation platform('com.fasterxml.jackson:jackson-bom:' + property('jacksonVersion'))
    // https://mvnrepository.com/artifact/com.gradleup.shadow/com.gradleup.shadow.gradle.plugin
    implementation 'com.gradleup.shadow:com.gradleup.shadow.gradle.plugin:9.4.3'
    // https://mvnrepository.com/artifact/com.vanniktech.maven.publish/com.vanniktech.maven.publish.gradle.plugin
    implementation 'com.vanniktech.maven.publish:com.vanniktech.maven.publish.gradle.plugin:0.37.0'
}
