rootProject.name = 'java-projects'
includeBuild 'gradle/buildPlugins'

def javaVersion = JavaVersion.current()

include ':cli:jgit-cli'
include ':cli:killport'
include ':cli:yaml2json'
include ':lib:ds'
include ':lib:picocli-logback-level-mixin'
include ':lib:spring:app'
include ':lib:spring:https-customizer'
include ':lib:spring:https-customizer-autoconfigure'
include ':lib:spring:json-logging-listener'
include ':lib:spring:json-logging-listener-demo'
include ':lib:spring:otel-logback-appender'
include ':lib:spring:otel-logging-listener'
include ':lib:spring:otel-logging-listener-demo'
include ':lib:throwables'
if (javaVersion >= JavaVersion.VERSION_21)
    include ':system:exec'
include ':system:infer-platform'
include ':system:terminal:supports-hyperlinks'
