plugins {
    id 'info.ankin.projects.library-conventions'
}

version = file('version.txt').text.trim()
description = 'verbosity level adjuster for use as a picocli mixin'

enableConventionConstraints()
dependencies {
    implementation 'ch.qos.logback:logback-classic:1.5.37'
    implementation 'info.picocli:picocli'
}
