import com.vanniktech.maven.publish.*

plugins {
    id 'info.ankin.projects.conventions'
    id 'java-library'
    id 'com.vanniktech.maven.publish'
}

java {
    // withJavadocJar()
    withSourcesJar()
}

/*
https://vanniktech.github.io/gradle-maven-publish-plugin/central/#secrets

scp ${somewhere_safe}:~/.ssh/maven-central.* ~/.ssh/

export ORG_GRADLE_PROJECT_mavenCentralUsername=$(cat ~/.ssh/maven-central.token.xml | grep -m1 -oP '(?<=<username>).*?(?=</username>)')
export ORG_GRADLE_PROJECT_mavenCentralPassword=$(cat ~/.ssh/maven-central.token.xml | grep -m1 -oP '(?<=<password>).*?(?=</password>)')
export ORG_GRADLE_PROJECT_signingInMemoryKey="$(cat ~/.ssh/maven-central.key.pgp)"

aws ssm put-parameter --type SecureString --name /maven-central/token --value file://.ssh/maven-central.token.xml
aws ssm put-parameter --type SecureString --name /maven-central/key --value file://.ssh/maven-central.key.pgp

ORG_GRADLE_PROJECT_signingInMemoryKeyId=12345678            # Optional
ORG_GRADLE_PROJECT_signingInMemoryKeyPassword=some_password # If key was created with a password.
 */

boolean propertiesSet() {
    ['mavenCentralUsername', 'mavenCentralPassword', 'signingInMemoryKey'].every {
        project.providers.gradleProperty(it).isPresent()
    }
}

if (propertiesSet())
    mavenPublishing {
        configure(new JavaLibrary(new JavadocJar.None(), new SourcesJar.Sources()))
        // https://vanniktech.github.io/gradle-maven-publish-plugin/central/#uploading-with-automatic-publishing
        publishToMavenCentral(true, DeploymentValidation.VALIDATED)
        signAllPublications()

        checksums(Checksum.MD5, Checksum.SHA1, Checksum.SHA512) // requirements + good hash
        excludeSignatureChecksums(false)

        pom {
            name = project.name
            description = project.description ?: project.name
            url = 'https://github.com/ankin/info.ankin.projects'

            licenses {
                license {
                    name = 'The Apache License, Version 2.0'
                    url = 'https://www.apache.org/licenses/LICENSE-2.0.txt'
                }
            }

            developers {
                developer {
                    id = 'alexanderankin'
                    name = 'David Ankin'
                }
            }

            scm {
                url = 'https://github.com/ankin/info.ankin.projects' // change me
                connection = 'scm:git:https://github.com/ankin/info.ankin.projects.git'
                developerConnection = 'scm:git:ssh://git@github.com/ankin/info.ankin.projects.git'
            }
        }
    }

/*
# install pgpainless-cli pre-requisites
sdk install java 11.0.31-tem # must be installed
sdk install java 21.0.11-tem # install 21 last, actually use that

# install pgpainless-cli
export GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
git clone git@github.com:pgpainless/pgpainless.git || git clone https://github.com/pgpainless/pgpainless.git
cd pgpainless
./gradlew :pgpainless-cli:installDist
ln -s $PWD/pgpainless-cli/build/install/pgpainless-cli/bin/pgpainless-cli ~/.local/bin/ # or other location in your PATH

# generate key
uid="$(git config user.name) <$(git config user.email)>" && [ "${uid}" != " <>" ] && pgpainless-cli generate-key "${uid}" > maven-central.key.pgp
pgpainless-cli extract-cert < maven-central.key.pgp > maven-central.public.pgp

# backup key
#scp maven-central.key.pgp  maven-central.public.pgp ${somewhere_safe}
mv maven-central.key.pgp  maven-central.public.pgp ~/.ssh/

# then upload
https://keyserver.ubuntu.com/
*/
