plugins {
    id 'info.ankin.projects.conventions'
}

// setting up a new group :(
group = 'info.ankin.projects.spring'

dependencies {
    implementation platform('org.springframework.boot:spring-boot-dependencies:3.5.3')
    annotationProcessor platform('org.springframework.boot:spring-boot-dependencies:3.5.3')
    implementation platform('org.springframework.cloud:spring-cloud-dependencies:2025.0.0')

    // https://mvnrepository.com/artifact/io.opentelemetry/opentelemetry-bom
    implementation platform('io.opentelemetry:opentelemetry-bom:1.54.0')
}
