on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/picocli-logback-level-mixin.yaml
      - lib/picocli-logback-level-mixin/**
    types:
      - opened
      - synchronize
      - closed

env:
  GRADLE_SUBPROJECT_DIR: lib/picocli-logback-level-mixin
  GRADLE_SUBPROJECT: ':lib:picocli-logback-level-mixin'

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25
          cache: gradle
      - { uses: gradle/actions/setup-gradle@v6, with: { cache-overwrite-existing: true } }
      - run: './gradlew ${{ env.GRADLE_SUBPROJECT }}:build'
  version:
    runs-on: ubuntu-latest
    outputs:
      VERSION_CHANGED: ${{ steps.compare.outputs.VERSION_CHANGED }}
    steps:
      - { uses: actions/checkout@v7, with: { fetch-depth: 0 } }
      - { uses: tj-actions/changed-files@v47, id: changed_files }
      - run: |
          file=${{ env.GRADLE_SUBPROJECT_DIR }}/version.txt
          if ! echo '${{ steps.changed_files.outputs.modified_files }}' | tr ' ' '\n' | grep '^'${file}'$'
          then
            echo "VERSION_CHANGED=" | tee -a "${GITHUB_OUTPUT}"
          else
            echo "VERSION_CHANGED=1" | tee -a "${GITHUB_OUTPUT}"
          fi
        id: compare

  publish:
    permissions:
      contents: read
      id-token: write
    needs:
      - build
      - version
    if: github.event.pull_request.merged == true && needs.version.outputs.VERSION_CHANGED != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25
          cache: gradle
      - { uses: gradle/actions/setup-gradle@v6, with: { cache-overwrite-existing: true } }
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'us-east-1'
          role-to-assume: arn:aws:iam::662610805887:role/prod-ssm-gha-read-maven-central-role
      - run: |
          params=$(aws ssm get-parameters-by-path --path /maven-central | jq -c)
          eval $(echo "${params}" | jq -r '.Parameters[] | ("export " + (.Name | gsub("[/-]"; "_")) + "='"'"'" + (.Value | tojson) + "'"'"';")')
          export ORG_GRADLE_PROJECT_mavenCentralUsername=$(echo ${_maven_central_token} | jq -r | grep -m1 -oP '(?<=<username>).*?(?=</username>)')
          export ORG_GRADLE_PROJECT_mavenCentralPassword=$(echo ${_maven_central_token} | jq -r | grep -m1 -oP '(?<=<password>).*?(?=</password>)')
          export ORG_GRADLE_PROJECT_signingInMemoryKey="$(echo ${_maven_central_key} | jq -r)"
          ./gradlew ${{ env.GRADLE_SUBPROJECT }}:publishToMavenCentral
